### ISSUE TITLE
self.$element is undefined

### ISSUE THREAD

**Issue by gandaldf** [citrusmist/curtain.js#7]
I have a simple structure with just two panels... everything works right but when I put an <img> element in one of these panel it stucks with this error:

detailed error: TypeError: self.$element is undefined
error source line 521: elems = self.$element.find('img'),

can you help me, please?

**Comment by artificer** [comment]
Is there anywhere I could see the code in action?

**Comment by gandaldf** [comment]
Yep, sorry!
Here is the code:

http://pastebin.com/2P3RK5A1

try to delete the image and the scroll will start to work.
what do you think?

**Comment by gandaldf** [comment]
Excuse me, have you tested it? Did you find a solution?

**Comment by artificer** [comment]
There are some issues with the detection of images being loaded. The plugins implementation of this is a little naive. 

You will need to use Desandro's imagesLoaded (https://github.com/desandro/imagesloaded).  Add it to your document after JQuery and the curtains plugin should recognise its presence and use this instead for detecting loading of images.
